//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orayo {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orayo.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }

        public static string AutoStartDisabled {
            get {
                return ResourceManager.GetString("AutoStartDisabled", resourceCulture);
            }
        }

        public static string AutoStartEnabled {
            get {
                return ResourceManager.GetString("AutoStartEnabled", resourceCulture);
            }
        }

        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }

        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }

        public static string ButtonCheckUpdate {
            get {
                return ResourceManager.GetString("ButtonCheckUpdate", resourceCulture);
            }
        }

        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }

        public static string ButtonFormat {
            get {
                return ResourceManager.GetString("ButtonFormat", resourceCulture);
            }
        }

        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }

        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }

        public static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }

        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }

        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }

        public static string ButtonUpdateAndRestart {
            get {
                return ResourceManager.GetString("ButtonUpdateAndRestart", resourceCulture);
            }
        }

        public static string ConfigHint {
            get {
                return ResourceManager.GetString("ConfigHint", resourceCulture);
            }
        }

        public static string EmptyHint {
            get {
                return ResourceManager.GetString("EmptyHint", resourceCulture);
            }
        }

        public static string ErrAutoStartFailed {
            get {
                return ResourceManager.GetString("ErrAutoStartFailed", resourceCulture);
            }
        }

        public static string ErrCannotDelete {
            get {
                return ResourceManager.GetString("ErrCannotDelete", resourceCulture);
            }
        }

        public static string ErrCannotDeleteActive {
            get {
                return ResourceManager.GetString("ErrCannotDeleteActive", resourceCulture);
            }
        }

        public static string ErrCannotDetermineExePath {
            get {
                return ResourceManager.GetString("ErrCannotDetermineExePath", resourceCulture);
            }
        }

        public static string ErrCannotShare {
            get {
                return ResourceManager.GetString("ErrCannotShare", resourceCulture);
            }
        }

        public static string ErrCannotShareProtocol {
            get {
                return ResourceManager.GetString("ErrCannotShareProtocol", resourceCulture);
            }
        }

        public static string ErrCannotStartTunBroker {
            get {
                return ResourceManager.GetString("ErrCannotStartTunBroker", resourceCulture);
            }
        }

        public static string ErrCannotStartXray {
            get {
                return ResourceManager.GetString("ErrCannotStartXray", resourceCulture);
            }
        }

        public static string ErrCannotTest {
            get {
                return ResourceManager.GetString("ErrCannotTest", resourceCulture);
            }
        }

        public static string ErrCloseTunForTest {
            get {
                return ResourceManager.GetString("ErrCloseTunForTest", resourceCulture);
            }
        }

        public static string ErrConnectionFailed {
            get {
                return ResourceManager.GetString("ErrConnectionFailed", resourceCulture);
            }
        }

        public static string ErrConnectionFailedMsg {
            get {
                return ResourceManager.GetString("ErrConnectionFailedMsg", resourceCulture);
            }
        }

        public static string ErrDnsJsonEmpty {
            get {
                return ResourceManager.GetString("ErrDnsJsonEmpty", resourceCulture);
            }
        }

        public static string ErrDnsJsonMissingServers {
            get {
                return ResourceManager.GetString("ErrDnsJsonMissingServers", resourceCulture);
            }
        }

        public static string ErrDnsJsonNotObject {
            get {
                return ResourceManager.GetString("ErrDnsJsonNotObject", resourceCulture);
            }
        }

        public static string ErrDnsServerInvalid {
            get {
                return ResourceManager.GetString("ErrDnsServerInvalid", resourceCulture);
            }
        }

        public static string ErrDownloadEmpty {
            get {
                return ResourceManager.GetString("ErrDownloadEmpty", resourceCulture);
            }
        }

        public static string ErrEditorTimeout {
            get {
                return ResourceManager.GetString("ErrEditorTimeout", resourceCulture);
            }
        }

        public static string ErrLoopbackFailed {
            get {
                return ResourceManager.GetString("ErrLoopbackFailed", resourceCulture);
            }
        }

        public static string ErrLoopbackNotFound {
            get {
                return ResourceManager.GetString("ErrLoopbackNotFound", resourceCulture);
            }
        }

        public static string ErrMissingConfig {
            get {
                return ResourceManager.GetString("ErrMissingConfig", resourceCulture);
            }
        }

        public static string ErrMonacoInitFailed {
            get {
                return ResourceManager.GetString("ErrMonacoInitFailed", resourceCulture);
            }
        }

        public static string ErrMonacoLoadFailed {
            get {
                return ResourceManager.GetString("ErrMonacoLoadFailed", resourceCulture);
            }
        }

        public static string ErrPortConflict {
            get {
                return ResourceManager.GetString("ErrPortConflict", resourceCulture);
            }
        }

        public static string ErrPortConflictLegacy {
            get {
                return ResourceManager.GetString("ErrPortConflictLegacy", resourceCulture);
            }
        }

        public static string ErrPortConflictUnknown {
            get {
                return ResourceManager.GetString("ErrPortConflictUnknown", resourceCulture);
            }
        }

        public static string ErrRequestEmpty {
            get {
                return ResourceManager.GetString("ErrRequestEmpty", resourceCulture);
            }
        }

        public static string ErrRequestInvalid {
            get {
                return ResourceManager.GetString("ErrRequestInvalid", resourceCulture);
            }
        }

        public static string ErrRoutingJsonEmpty {
            get {
                return ResourceManager.GetString("ErrRoutingJsonEmpty", resourceCulture);
            }
        }

        public static string ErrRoutingJsonMissingRules {
            get {
                return ResourceManager.GetString("ErrRoutingJsonMissingRules", resourceCulture);
            }
        }

        public static string ErrRoutingJsonNotObject {
            get {
                return ResourceManager.GetString("ErrRoutingJsonNotObject", resourceCulture);
            }
        }

        public static string ErrRoutingRuleMissingTag {
            get {
                return ResourceManager.GetString("ErrRoutingRuleMissingTag", resourceCulture);
            }
        }

        public static string ErrRoutingRuleNotObject {
            get {
                return ResourceManager.GetString("ErrRoutingRuleNotObject", resourceCulture);
            }
        }

        public static string ErrRoutingRuleType {
            get {
                return ResourceManager.GetString("ErrRoutingRuleType", resourceCulture);
            }
        }

        public static string ErrTunBrokerEmptyResponse {
            get {
                return ResourceManager.GetString("ErrTunBrokerEmptyResponse", resourceCulture);
            }
        }

        public static string ErrTunBrokerError {
            get {
                return ResourceManager.GetString("ErrTunBrokerError", resourceCulture);
            }
        }

        public static string ErrTunBrokerNoResponse {
            get {
                return ResourceManager.GetString("ErrTunBrokerNoResponse", resourceCulture);
            }
        }

        public static string ErrTunBrokerNoResponseWith {
            get {
                return ResourceManager.GetString("ErrTunBrokerNoResponseWith", resourceCulture);
            }
        }

        public static string ErrTunBrokerStartFailed {
            get {
                return ResourceManager.GetString("ErrTunBrokerStartFailed", resourceCulture);
            }
        }

        public static string ErrTunBrokerXrayFailed {
            get {
                return ResourceManager.GetString("ErrTunBrokerXrayFailed", resourceCulture);
            }
        }

        public static string ErrTunModeError {
            get {
                return ResourceManager.GetString("ErrTunModeError", resourceCulture);
            }
        }

        public static string ErrTunStartFailed {
            get {
                return ResourceManager.GetString("ErrTunStartFailed", resourceCulture);
            }
        }

        public static string ErrUacCancelled {
            get {
                return ResourceManager.GetString("ErrUacCancelled", resourceCulture);
            }
        }

        public static string ErrUpdateVersionLower {
            get {
                return ResourceManager.GetString("ErrUpdateVersionLower", resourceCulture);
            }
        }

        public static string ErrUnknownCommand {
            get {
                return ResourceManager.GetString("ErrUnknownCommand", resourceCulture);
            }
        }

        public static string ErrWebView2NotReady {
            get {
                return ResourceManager.GetString("ErrWebView2NotReady", resourceCulture);
            }
        }

        public static string ErrWintunNotFound {
            get {
                return ResourceManager.GetString("ErrWintunNotFound", resourceCulture);
            }
        }

        public static string ErrXrayExitImmediately {
            get {
                return ResourceManager.GetString("ErrXrayExitImmediately", resourceCulture);
            }
        }

        public static string ErrXrayExeNotFound {
            get {
                return ResourceManager.GetString("ErrXrayExeNotFound", resourceCulture);
            }
        }

        public static string ErrXrayNotFound {
            get {
                return ResourceManager.GetString("ErrXrayNotFound", resourceCulture);
            }
        }

        public static string ErrXrayNotInPackage {
            get {
                return ResourceManager.GetString("ErrXrayNotInPackage", resourceCulture);
            }
        }

        public static string ErrXrayStartFailed {
            get {
                return ResourceManager.GetString("ErrXrayStartFailed", resourceCulture);
            }
        }

        public static string GeoDescription {
            get {
                return ResourceManager.GetString("GeoDescription", resourceCulture);
            }
        }

        public static string GeoFiles {
            get {
                return ResourceManager.GetString("GeoFiles", resourceCulture);
            }
        }

        public static string GlobalProxyMode {
            get {
                return ResourceManager.GetString("GlobalProxyMode", resourceCulture);
            }
        }

        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }

        public static string LabelAllowInsecure {
            get {
                return ResourceManager.GetString("LabelAllowInsecure", resourceCulture);
            }
        }

        public static string LabelEncryption {
            get {
                return ResourceManager.GetString("LabelEncryption", resourceCulture);
            }
        }

        public static string LabelHttpPort {
            get {
                return ResourceManager.GetString("LabelHttpPort", resourceCulture);
            }
        }

        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }

        public static string LabelNetwork {
            get {
                return ResourceManager.GetString("LabelNetwork", resourceCulture);
            }
        }

        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }

        public static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }

        public static string LabelProtocol {
            get {
                return ResourceManager.GetString("LabelProtocol", resourceCulture);
            }
        }

        public static string LabelSocksPort {
            get {
                return ResourceManager.GetString("LabelSocksPort", resourceCulture);
            }
        }

        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }

        public static string LatencyTimeout {
            get {
                return ResourceManager.GetString("LatencyTimeout", resourceCulture);
            }
        }

        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        public static string LogConfig {
            get {
                return ResourceManager.GetString("LogConfig", resourceCulture);
            }
        }

        public static string LogError {
            get {
                return ResourceManager.GetString("LogError", resourceCulture);
            }
        }

        public static string LogException {
            get {
                return ResourceManager.GetString("LogException", resourceCulture);
            }
        }

        public static string LogStart {
            get {
                return ResourceManager.GetString("LogStart", resourceCulture);
            }
        }

        public static string LogStartFailed {
            get {
                return ResourceManager.GetString("LogStartFailed", resourceCulture);
            }
        }

        public static string LogStopped {
            get {
                return ResourceManager.GetString("LogStopped", resourceCulture);
            }
        }

        public static string LogXrayExited {
            get {
                return ResourceManager.GetString("LogXrayExited", resourceCulture);
            }
        }

        public static string LoopbackDescription {
            get {
                return ResourceManager.GetString("LoopbackDescription", resourceCulture);
            }
        }

        public static string LoopbackManager {
            get {
                return ResourceManager.GetString("LoopbackManager", resourceCulture);
            }
        }

        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }

        public static string AboutOrayo {
            get {
                return ResourceManager.GetString("AboutOrayo", resourceCulture);
            }
        }

        public static string AppVersionFormat {
            get {
                return ResourceManager.GetString("AppVersionFormat", resourceCulture);
            }
        }

        public static string AppVersionLoading {
            get {
                return ResourceManager.GetString("AppVersionLoading", resourceCulture);
            }
        }

        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }

        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }

        public static string MenuShare {
            get {
                return ResourceManager.GetString("MenuShare", resourceCulture);
            }
        }

        public static string MsgClipboardFailed {
            get {
                return ResourceManager.GetString("MsgClipboardFailed", resourceCulture);
            }
        }

        public static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }

        public static string MsgConfirmLanguageChange {
            get {
                return ResourceManager.GetString("MsgConfirmLanguageChange", resourceCulture);
            }
        }

        public static string MsgCopied {
            get {
                return ResourceManager.GetString("MsgCopied", resourceCulture);
            }
        }

        public static string MsgImportDone {
            get {
                return ResourceManager.GetString("MsgImportDone", resourceCulture);
            }
        }

        public static string MsgNewVersion {
            get {
                return ResourceManager.GetString("MsgNewVersion", resourceCulture);
            }
        }

        public static string MsgNoClipboard {
            get {
                return ResourceManager.GetString("MsgNoClipboard", resourceCulture);
            }
        }

        public static string MsgNoClipboardContent {
            get {
                return ResourceManager.GetString("MsgNoClipboardContent", resourceCulture);
            }
        }

        public static string MsgNoNewNodes {
            get {
                return ResourceManager.GetString("MsgNoNewNodes", resourceCulture);
            }
        }

        public static string MsgShareLinkCopied {
            get {
                return ResourceManager.GetString("MsgShareLinkCopied", resourceCulture);
            }
        }

        public static string MoreDescription {
            get {
                return ResourceManager.GetString("MoreDescription", resourceCulture);
            }
        }

        public static string PlaceholderEncryption {
            get {
                return ResourceManager.GetString("PlaceholderEncryption", resourceCulture);
            }
        }

        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }

        public static string ProxyDisabled {
            get {
                return ResourceManager.GetString("ProxyDisabled", resourceCulture);
            }
        }

        public static string ProxyEnabled {
            get {
                return ResourceManager.GetString("ProxyEnabled", resourceCulture);
            }
        }

        public static string RouteRuleCount {
            get {
                return ResourceManager.GetString("RouteRuleCount", resourceCulture);
            }
        }

        public static string RouteSummaryNormal {
            get {
                return ResourceManager.GetString("RouteSummaryNormal", resourceCulture);
            }
        }

        public static string RouteSummaryTun {
            get {
                return ResourceManager.GetString("RouteSummaryTun", resourceCulture);
            }
        }

        public static string RoutingRuleMode {
            get {
                return ResourceManager.GetString("RoutingRuleMode", resourceCulture);
            }
        }

        public static string SectionAdvanced {
            get {
                return ResourceManager.GetString("SectionAdvanced", resourceCulture);
            }
        }

        public static string SectionBasic {
            get {
                return ResourceManager.GetString("SectionBasic", resourceCulture);
            }
        }

        public static string SectionProtocol {
            get {
                return ResourceManager.GetString("SectionProtocol", resourceCulture);
            }
        }

        public static string SectionTransport {
            get {
                return ResourceManager.GetString("SectionTransport", resourceCulture);
            }
        }

        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }

        public static string StatusAlreadyLatest {
            get {
                return ResourceManager.GetString("StatusAlreadyLatest", resourceCulture);
            }
        }

        public static string StatusCheckingUpdate {
            get {
                return ResourceManager.GetString("StatusCheckingUpdate", resourceCulture);
            }
        }

        public static string StatusCurrentSelected {
            get {
                return ResourceManager.GetString("StatusCurrentSelected", resourceCulture);
            }
        }

        public static string StatusDisconnected {
            get {
                return ResourceManager.GetString("StatusDisconnected", resourceCulture);
            }
        }

        public static string StatusDownloadingUpdate {
            get {
                return ResourceManager.GetString("StatusDownloadingUpdate", resourceCulture);
            }
        }

        public static string StatusDownloadingXray {
            get {
                return ResourceManager.GetString("StatusDownloadingXray", resourceCulture);
            }
        }

        public static string StatusGeoApplied {
            get {
                return ResourceManager.GetString("StatusGeoApplied", resourceCulture);
            }
        }

        public static string StatusGeoDownloaded {
            get {
                return ResourceManager.GetString("StatusGeoDownloaded", resourceCulture);
            }
        }

        public static string StatusLoopbackOpened {
            get {
                return ResourceManager.GetString("StatusLoopbackOpened", resourceCulture);
            }
        }

        public static string StatusNotSelected {
            get {
                return ResourceManager.GetString("StatusNotSelected", resourceCulture);
            }
        }

        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }

        public static string StatusUpdateCancelled {
            get {
                return ResourceManager.GetString("StatusUpdateCancelled", resourceCulture);
            }
        }

        public static string StatusUpdateDownloaded {
            get {
                return ResourceManager.GetString("StatusUpdateDownloaded", resourceCulture);
            }
        }

        public static string StatusUpdateNotSupported {
            get {
                return ResourceManager.GetString("StatusUpdateNotSupported", resourceCulture);
            }
        }

        public static string StatusUpdatingGeo {
            get {
                return ResourceManager.GetString("StatusUpdatingGeo", resourceCulture);
            }
        }

        public static string StatusXrayApplied {
            get {
                return ResourceManager.GetString("StatusXrayApplied", resourceCulture);
            }
        }

        public static string StatusXrayDownloaded {
            get {
                return ResourceManager.GetString("StatusXrayDownloaded", resourceCulture);
            }
        }

        public static string TitleAddServer {
            get {
                return ResourceManager.GetString("TitleAddServer", resourceCulture);
            }
        }

        public static string TitleDeleteServer {
            get {
                return ResourceManager.GetString("TitleDeleteServer", resourceCulture);
            }
        }

        public static string TitleDNS {
            get {
                return ResourceManager.GetString("TitleDNS", resourceCulture);
            }
        }

        public static string TitleEditServer {
            get {
                return ResourceManager.GetString("TitleEditServer", resourceCulture);
            }
        }

        public static string TitleLanguageChange {
            get {
                return ResourceManager.GetString("TitleLanguageChange", resourceCulture);
            }
        }

        public static string TitleMore {
            get {
                return ResourceManager.GetString("TitleMore", resourceCulture);
            }
        }

        public static string TitleNewVersion {
            get {
                return ResourceManager.GetString("TitleNewVersion", resourceCulture);
            }
        }

        public static string TitleRoute {
            get {
                return ResourceManager.GetString("TitleRoute", resourceCulture);
            }
        }

        public static string TitleShareLink {
            get {
                return ResourceManager.GetString("TitleShareLink", resourceCulture);
            }
        }

        public static string TipLatencyTest {
            get {
                return ResourceManager.GetString("TipLatencyTest", resourceCulture);
            }
        }

        public static string TipManualAdd {
            get {
                return ResourceManager.GetString("TipManualAdd", resourceCulture);
            }
        }

        public static string TipMore {
            get {
                return ResourceManager.GetString("TipMore", resourceCulture);
            }
        }

        public static string TipPasteImport {
            get {
                return ResourceManager.GetString("TipPasteImport", resourceCulture);
            }
        }

        public static string ToggleSystemProxy {
            get {
                return ResourceManager.GetString("ToggleSystemProxy", resourceCulture);
            }
        }

        public static string ToggleTunMode {
            get {
                return ResourceManager.GetString("ToggleTunMode", resourceCulture);
            }
        }

        public static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }

        public static string TrayShowOrayo {
            get {
                return ResourceManager.GetString("TrayShowOrayo", resourceCulture);
            }
        }

        public static string TunHintOff {
            get {
                return ResourceManager.GetString("TunHintOff", resourceCulture);
            }
        }

        public static string TunHintOn {
            get {
                return ResourceManager.GetString("TunHintOn", resourceCulture);
            }
        }

        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }

        public static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }

        public static string WarnJobObjectAssign {
            get {
                return ResourceManager.GetString("WarnJobObjectAssign", resourceCulture);
            }
        }

        public static string WarnJobObjectFailed {
            get {
                return ResourceManager.GetString("WarnJobObjectFailed", resourceCulture);
            }
        }

        public static string WarnJobObjectLimit {
            get {
                return ResourceManager.GetString("WarnJobObjectLimit", resourceCulture);
            }
        }

        public static string XrayCore {
            get {
                return ResourceManager.GetString("XrayCore", resourceCulture);
            }
        }
    }
}
